;; Each new term in the Fibonacci sequence is generated by adding the previous
;; two terms. By starting with 1 and 2, the first 10 terms will be:
;;      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.

(defun million-fib ()
  "Calculate the terms of the Fibonacci sequence smaller than four million."
  (setq fibo (list 2 1))
  (setq next (+ (car fibo) (car (cdr fibo))))
  (while (< next 4000000)
    (push (+ (car fibo)
             (car (cdr fibo)))
          fibo)
    (setq next (+ (car fibo) (car (cdr fibo)))))
  fibo)

(defun sum-even (lis)
  "Calculate the sum of the even numbers of a list."
  (setq res 0)
  (setq curr (car lis))
  (setq next (cdr lis))
  (while (not (null curr))
    (if (= (% curr 2) 0)
        (setq res (+ res curr)))
    (setq curr (car next))
    (setq next (cdr next)))
  res)

(sum-even (million-fib))
